// Painting data — this is the ONLY file you need to edit when adding/removing art.
// Each entry: { file: "filename.jpg", title: "Painting Title" }
// Images go in images/paintings/

const paintings = [
  { file: "MIRADA_683x1024.jpg", title: "Mirada" },
  { file: "AZUL Y PLATA_683x1024.jpg", title: "Azul y Plata" },
  { file: "TROVADOR_683x1024.jpg", title: "Trovador" },
  { file: "ROJO INSINUADO_683x1024.jpg", title: "Rojo Insinuado" },
  { file: "AZUL NEGRO Y CAFE_683x1024.jpg", title: "Azul Negro y Café" },
  { file: "TE_683x1024.jpg", title: "Té" },
  { file: "ASOMO_683x1024.jpg", title: "Asomo" },
  { file: "BAILE_668x1024.jpg", title: "Baile" },
  { file: "ESCALERA_683x1024.jpg", title: "Escalera" },
  { file: "COMIENDO LUNA_683x1024.jpg", title: "Comiendo Luna" },
  { file: "CABALLO _683x1024.jpg", title: "Caballo" },
  { file: "CALACA _683x1024.jpg", title: "Calaca" },
  { file: "COMPUNGIDO_683x1024.jpg", title: "Compungido" },
  { file: "DIVIDIDO_683x1024.jpg", title: "Dividido" },
  { file: "FIESTA_683x1024.jpg", title: "Fiesta" },
  { file: "LAGRIMA_683x1024.jpg", title: "Lágrima" },
  { file: "Maderas_UL.jpeg", title: "Maderas" },
  { file: "PAREJA EN ROJO _683x1024.jpg", title: "Pareja en Rojo" },
  { file: "SONRISA_683x1024.jpg", title: "Sonrisa" },
  { file: "SURGIMIENTO_683x1024.jpg", title: "Surgimiento" },
  { file: "TORBELLINO_683x1024.jpg", title: "Torbellino" },
  { file: "VENTANA_683x1024.jpg", title: "Ventana" },
  { file: "DE ESPALDA _683x1024.jpg", title: "De Espalda" },
  { file: "RED EN ROJO _768x966.jpg", title: "Red en Rojo" },
  { file: "PROCESION OBRA SUBASTA LILA_768x1024.jpg", title: "Procesión" },
  { file: "OBRA LUIS SUBASTA VERO 2_768x1012.jpg", title: "Obra Luis Subasta Vero" },
  { file: "Guaje_UL.jpeg", title: "Guaje" },
  { file: "Cara_blanca_UL.jpg", title: "Cara Blanca" },
  { file: "Circulo_ext_UL.jpeg", title: "Círculo" },
  // Landscape orientation
  { file: "CONTEMPLANDO_1024x683.jpg", title: "Contemplando" },
  { file: "CUADROS_1024x683.jpg", title: "Cuadros" },
  { file: "FOSIL_1024x683.jpg", title: "Fósil" },
  { file: "GESTO_1024x683.jpg", title: "Gesto" },
  { file: "PIANISTA_1024x683.jpg", title: "Pianista" },
  { file: "Azul_horizontal_UL.jpg", title: "Azul Horizontal" },
];
